POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Deadhouse Gates",
    "author": "Steven Erickson",
    "url": "www.malazan.com",
    "likes": 15000
}

####
GET http://localhost:3003/api/blogs