POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Harry Potter",
    "author": "JK Rowling",
    "url": "www.harrypotter.com",
    "likes": 50000
}

####
GET http://localhost:3003/api/blogs