POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Game of Thrones",
    "author": "GRR Martin",
    "url": "www.asongoficeandfire.com",
    "likes": 25000
}

####
GET http://localhost:3003/api/blogs